### ISSUE TITLE
The connection option of MqttClientSubscriber doesn't contain credentials

### ISSUE THREAD

**Issue by Saturnoul** [SeppPenner/MQTTnet.TestApp.WinForm#1]
The connection option of MqttClientSubscriber should include credentials, or it can't connect to the local MqttServer

**Comment by SeppPenner** [comment]
That's the problem when you don't write such projects on your own :D This project was originally created by @grammyleung. I will try to fix this soon.

**Comment by Saturnoul** [comment]
Your work is really helpful, and I am just trying to help, thanks.
