### ISSUE TITLE
Client connection to external server

### ISSUE THREAD

**Issue by helmidreijer** [SeppPenner/MQTTnet.TestApp.WinForm#3]
The MQTTnet.TestApp.Winform works great for with "local server"...and remote servers !.. network issue solved

**Comment by SeppPenner** [comment]
Sorry for the late reply. Did you get it to work properly?

**Comment by helmidreijer** [comment]
Hi SeppPenner

Yes, I got it working nicely with local server as well as ***@***.*** It helped to learn more about event management using the mqtt protocol.

I am however struggling to get an Axis camera P1455-le to publish to the MQTTnet TestApp. It has the options for
MQTT over TCP port 1883
MQLL over ssl port 8883
MQTT over WinSocket 
MQTT over WinSocket Secure port 443
None of these hiwvwe can communicate with the MQTTnet app?

Any advice ?

Many thanks !



Helmi Dreijer ! Stellenbosch ! +2783 600 5274 ! ***@***.*** ***@***.***> ! Skype: helmidreijer








On 18 Apr 2021, at 5:35 PM, HansM ***@***.***> wrote:


Sorry for the late reply. Did you get it to work properly?

**Comment by SeppPenner** [comment]
@helmidreijer I can only guess. Maybe, there is a firewall issue in between or something? Normally, there should be no connection issues.

**Comment by helmidreijer** [comment]
HI

BTW,  MQTT event reporting from Axis cameras to my local MQTTnet server
works great for WinForms .NET5

I would now like to implement a client in ASP.NET Core 5.0.  I saw there
was a solution ?

Many thanks !
Helmi



I

**Comment by SeppPenner** [comment]
You can use the client as in WinForms, following the wiki under https://github.com/chkr1011/MQTTnet/wiki/Client. There is no real difference between ASP.Net Core (on Net5) and WinForms (Net5) in case of the MQTTnet client setup.

You can setup a MQTT client in every page or controller or whatever you use in ASP.Net.

The other way is to setup a MQTT client once and inject it via [dependency injection](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0), but I don't know how experienced you are with that.
